### ISSUE TITLE
Records lost when turning Internet Threat Management on or off

### ISSUE THREAD

**Issue by davyike** [evaneaston/udm-host-records#4]
When I turn the UDMP Internet Threat Management on or off (UDM-Pro 1.9.0.3413), the host records reset back to defaults.

Doubt you can do anything about this, but would be good to include in the README.md? And maybe verify if the same happens to you?

**Comment by evaneaston** [comment]
@davyike  Thank you for letting me know.  At the very least I'll update the README.

I could, perhaps, store the entries on disk when adding them via the API calls and then periodically re-add/update them on a schedule.  But I'll have to see what the unifi-os way to schedule things is since cron doesn't seem to be included.   Systemd timers?  Not sure if they survive reboots or need to be recreated at boot time 😢.

**Comment by davyike** [comment]
Yeah, might be more effort than it's worth? 😬 My previous approach had a script in `/mnt/data/on_boot.d` that is supposed to run on reboot, but never did... hard to tell which system tools can be relied on.

**Comment by evaneaston** [comment]
I'm closing this in favor of the more general #5 .  See [this comment](https://github.com/evaneaston/udm-host-records/issues/5#issuecomment-869833742).
